package constant

const DEFAULT_WINDOW_WIDTH = 760
const DEFAULT_WINDOW_HEIGHT = 540
const MAX_WINDOW_WIDTH = 960
const MAX_WINDOW_HEIGHT = 620
const MIN_WINDOW_WIDTH = 680
const MIN_WINDOW_HEIGHT = 480
